version: '2'
services:
    simplemonolith-app:
        image: simplemonolith
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://simplemonolith-mysql:3306/simplemonolith?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simplemonolith-mysql:
        extends:
            file: mysql.yml
            service: simplemonolith-mysql
